### PR TITLE
Drupal compat

### PR DESCRIPTION
**Pull request by jeffam**
- Removed the composer.lock file.
- Lowered the version requirement for symfony/yaml to allow better compatibility with [drupal/core version 8.4](https://github.com/drupal/core/blob/d4be8e12d9e8b4db82ece760c632213247f56fa7/composer.json#L20).

### CODE REVIEW

**Comment by EvanLovely** [comment]
@jeffam Thanks! Out of curiosity, why did you remove `composer.lock`? Also, I've released v1.0.1 after merging in your changes.

**Comment by jeffam** [comment]
@EvanLovely I deleted it because I had read [this article (or something like it)](https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/) at some point and remembered this nugget:

> Always commit composer.lock for applications.
> Never commit composer.lock for components. 

So I wasn't sure what composer would do when resolving the `symfony/yaml` package when that package had a lock file requiring a later version than I needed. Turns out, when I read that article more closely, the project composer will ignore the package lock file, so I could have left it in.

**Comment by EvanLovely** [comment]
@jeffam Ah! Yep, same in node world! And yarn does that same behavior: dependencies lock files are simply ignored.

**Comment by EvanLovely** [comment]
Thanks again for the contribution!

**Pull request merged**
